### ISSUE TITLE
README grammar mistake

### ISSUE THREAD

**Issue by razrLeLe** [guodongxiaren/README#1]
> This README.md is used to testing all kinds of syntax of GitHub Flavored Markdown.

 you'd better correct it as 

> This README.md is used for testing all kinds of syntax of GitHub Flavored Markdown.

or

> This README.md is used to test all kinds of syntax of GitHub Flavored Markdown.

**Comment by perphyyoung** [comment]
我发现在你的源文件中，有些标题的·#·和标题文字间没有空格，我在使用 atom 编辑器查看时，这些标题都没有被引擎渲染成正确的格式
