### ISSUE TITLE
复选框列表制作任务清单

### ISSUE THREAD

**Issue by HeminWon** [guodongxiaren/README#10]
测试了一下，貌似现在不支持复选框列表了  我时在博客里面测试的，是我的方式不对么？

**Comment by endlesstravel** [comment]
可以啊，我这里README.md显示正常。我想是你的博客网站不支持完整的markdown语法导致的。

**Comment by guodongxiaren** [comment]
- [x] 呵呵
- [ ] 哪里不支持了
