### ISSUE TITLE
markdown中的图片怎么调整大小呢？

### ISSUE THREAD

**Issue by vipzrx** [guodongxiaren/README#11]

**Comment by endlesstravel** [comment]
貌似没有提供直接的语法

**Comment by guodongxiaren** [comment]
可以考虑在Markdown中直接嵌入HTML语法。是可以被成功解析的。

<img src="https://avatars3.githubusercontent.com/u/5945107"  width="40px" height="40px" />
<img src="https://avatars3.githubusercontent.com/u/5945107"  width="50px" height="50px" />

```
<img src="https://avatars3.githubusercontent.com/u/5945107"  width="40px" height="40px" />
<img src="https://avatars3.githubusercontent.com/u/5945107"  width="50px" height="50px" />
```
