### ISSUE TITLE
图片的问题

### ISSUE THREAD

**Issue by ryc787725121** [guodongxiaren/README#18]
如果是公司的私有仓库 比如 http://192.188.1.62/ios/项目 ，要在这个项目中显示图片，怎么显示，试了好多都不行只显示 占位文字了，求解答。

**Comment by EEPlat** [comment]
图片显示有特定的控制器，DOValueImage。

**Comment by ryc787725121** [comment]
显示的是占位文字，点击文字，后打开了一个新的网页，就显示了，请问，这是什么情况？望解答，谢谢了

**Comment by weikexin** [comment]
你看一下DOValueImage的代码，还有再看一下生成的html 代码。
