### ISSUE TITLE
为什么在简书或者csdn写好的粘贴过来不通用呢 

### ISSUE THREAD

**Issue by AndSync** [guodongxiaren/README#24]

**Comment by guodongxiaren** [comment]
Markdown语法不统一。github叫做github flavored markdown不是一般的markdown。不同平台对基础markdown语法都有扩展。即使是github本身，markdown语法也多次更新，比如我三年前写的markdown，到如今就不兼容了，导致排版错乱。所以最近我又更新了一个排版修复的版本。

**Comment by nickChenyx** [comment]
@guodongxiaren 的确 我还是在这里看到了 新的[Book](/Book) 的用法， 之前的 [Book](./Book)全崩了
