### ISSUE TITLE
请问github的表情在哪里？

### ISSUE THREAD

**Issue by qianjilou** [guodongxiaren/README#31]
smill

**Comment by guodongxiaren** [comment]
😄 
`:smile`

**Comment by AutuanLiu** [comment]
[可用表情表链接](https://github.com/guodongxiaren/README/blob/master/emoji.md)

一般输入 : + 表情名的前几个字母，GitHub会提示表情 @qianjilou 

* 所有符号均为 英文状态

**Comment by qianjilou** [comment]
😄 🛩   好的，谢谢！貌似看到了一个表情的仓库，忘记了地址，是王顶老师讲解的

**Comment by guodongxiaren** [comment]
王顶老师是谁？？

**Comment by qianjilou** [comment]
51CTO的一位讲师，在讲解git的时候，特别提到了你的proflie

**Comment by guodongxiaren** [comment]
哇。有视频地址吗？求URL。

**Comment by qianjilou** [comment]
http://edu.51cto.com/course/7845.html
【王顶】GitHub 开源之旅视频课程第一季：Git 入门(第4节)

**Comment by guodongxiaren** [comment]
可惜是收费的。。

**Comment by qianjilou** [comment]
我给帐号你用一下吧！767008349!
。。。。
。。。。
