### ISSUE TITLE
atom  markdown preview

### ISSUE THREAD

**Issue by worker000000** [guodongxiaren/README#37]
dear professor
I am using atom, I try to usr the emoji in your page, but the emoji can not show in my markdown, can you help me , thanks a lot.

![jxz9vdu2swag1jo l q7jw](https://user-images.githubusercontent.com/25199946/32311943-1af60fc4-bfd6-11e7-9183-f79952846309.png)

**Comment by guodongxiaren** [comment]
you can commit and push your markdown text to one of your GitHub's repos. emoji will appear one the GitHub website.
