### ISSUE TITLE
求助，搭建个人简易博客

### ISSUE THREAD

**Issue by afzj** [guodongxiaren/README#47]
你好，我是小白，想要用库自动转换的io网站搞一个简单的博客类的东西，放一些我自己写的文章上去，我想要搞一个目录，然后点击题目就可以直接下载或者访问我的文章，请问这个该怎么做呢，百度了好久，似乎这个太简单找不到啊，求助大神（可不可以将文件放在库里的文件夹然后在readme里点链接直接可以下载）

**Comment by Ienu** [comment]
你好，我不是大神。github有gist，是个人博客，如果你想公开应该有指定的方法。另外支持wiki。如果你想搭建更丰富的网页，我建议用IO，之前看过一些别人的，可以参考https://pages.github.com/。最后就是我的这种方式，通过markdown的md脚本。至于你说的将文件放在库里然后在readme里点击下载，我这种方式就可以实现了。

**Comment by guodongxiaren** [comment]
enjoy yourself.
