### ISSUE TITLE
似乎不能在文本块中添加文本链接

### ISSUE THREAD

**Issue by Daniellin1207** [guodongxiaren/README#63]
似乎不能在文本块中添加文本链接

**Comment by Audyzj** [comment]
应该可以的，你指的具体是什么地方？

**Comment by Daniellin1207** [comment]
输入:
(4 空格)这是较早时候的项目，现在计划重写一个，以提高熟练度~见[RTX项目](https://github.com/)
输出:
(文本块))这是较早时候的项目，现在计划重写一个，以提高熟练度~见[RTX项目](https://github.com/)

没有显示点选的 RTX项目链接
PS. 相同的[RTX项目](https://github.com/)在其他地方，不在文本块中则可以正常显示点选项目链接

**Comment by Daniellin1207** [comment]
> 输入:
> (4 空格)这是较早时候的项目，现在计划重写一个，以提高熟练度~见\[RTX项目](https://github.com/) 输出: (文本块))这是较早时候的项目，现在计划重写一个，以提高熟练度~见\[RTX项目](https://github.com/)
> 
> 没有显示点选的 RTX项目链接
> PS. 相同的[RTX项目](https://github.com/)在其他地方，不在文本块中则可以正常显示点选项目链接

这里直接就显示成点选链接了，但是我那不行诶，不知道怎么截图
