### ISSUE TITLE
何时使用markdown语法，何时应该使用html标签

### ISSUE THREAD

**Issue by AlpsSnow** [guodongxiaren/README#67]
markdown对html标签兼容，那么在实际使用过程中，有没有什么标准可以判断，应该使用markdown的书写方式，还是使用html的标签呢？
比方，想要显示一个图片，应该用下面哪一种呢？
1，![](https://gw.alipayobjects.com/zos/rmsportal/cPUduuYgROeJwRJSRuFK.png)
2，<img src=https://gw.alipayobjects.com/zos/rmsportal/cPUduuYgROeJwRJSRuFK.png>

**Comment by guodongxiaren** [comment]
mardown实现不了的用html
