### ISSUE TITLE
标签

### ISSUE THREAD

**Issue by lihe** [guodongxiaren/README#80]
![image](https://user-images.githubusercontent.com/48715622/87895677-99984180-ca78-11ea-85e9-88b890f7e7b7.png)
你好，这个蓝色的标签的语法是什么啊，找了很久都没找到

![image](https://user-images.githubusercontent.com/48715622/87895795-eaa83580-ca78-11ea-99f0-a4bcd6d75b11.png)

或者是这样的，该怎么写出来

**Comment by KagurazakaHanabi** [comment]
只是普通的图片，可搜索 GitHub Badge 了解一下

**Comment by lihe** [comment]
多谢

**Comment by guodongxiaren** [comment]
https://shields.io/

@lihe
